#ifndef YUTREL_DEFAULTLIT_INPUT_INCLUDED
#define YUTREL_DEFAULTLIT_INPUT_INCLUDED

TEXTURE2D(_BaseColorTex);
SAMPLER(sampler_BaseColorTex);

UNITY_INSTANCING_BUFFER_START(UnityPerMaterial)
    UNITY_DEFINE_INSTANCED_PROP(float4, _BaseColorTex_ST)
    UNITY_DEFINE_INSTANCED_PROP(float4, _Emissive)
UNITY_INSTANCING_BUFFER_END(UnityPerMaterial)

#endif
