#ifndef  YUTREL_DIRECTIONAL_LIGHT_PASS_INPUT_INCLUDED
#define  YUTREL_DIRECTIONAL_LIGHT_PASS_INPUT_INCLUDED

SAMPLER(_GBuffer_A);
SAMPLER(_GBuffer_B);
SAMPLER(_GBuffer_C);
SAMPLER(_SceneDepth);

#endif
