#ifndef YUTREL_UNLIT_INPUT_INCLUDED
#define YUTREL_UNLIT_INPUT_INCLUDED

TEXTURE2D(_MainTex);
SAMPLER(sampler_MainTex);

UNITY_INSTANCING_BUFFER_START(UnityPerMaterial)
    UNITY_DEFINE_INSTANCED_PROP(float4, _MainTex_ST)
    UNITY_DEFINE_INSTANCED_PROP(float4, _Emissive)
UNITY_INSTANCING_BUFFER_END(UnityPerMaterial)

#endif
